baseURL = "https://enerep.github.io/Blog123/"
languageCode = "en"

title = "Bat-Blog"

theme = "gokarna"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/526avijitgupta/gokarna"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false


[params]
  # URL for the avatar on homepage
  avatarURL = "images/avatar2.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-s"

  # Description to display on homepage
  description = "Unofficial. Just testing :/"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""

  # Links
  socialIcons = [
    {name = "instagram", url = "https://www.instagram.com/batochirchan?igshid=OGQ5ZDc2ODk2ZA%3D%3D&utm_source=qr"},
    {name = "email", url = "mailto:temp25118@gmail.com"}
  ]
